export const READ_CHARACTERS = 'READ_CHARACTERS';

export const CREATE_CHARACTER = 'CREATE_CHARACTER';

export const UPDATE_CHARACTER = 'UPDATE_CHARACTER';
export const UPDATE_CHARACTER_EDIT = 'UPDATE_CHARACTER_EDIT';

export const DELETE_CHARACTER = 'DELETE_CHARACTER';
